version: 2
machine: true
jobs:
  build:
    machine:
      image: ubuntu-2204:current
    working_directory: ~/circleci-java
    steps:
      - run:
          name: Install OpenJDK 11
          command: |
            sudo apt-get update && sudo apt-get install -y openjdk-11-jdk
            sudo update-java-alternatives --jre-headless --jre --set java-1.11.0-openjdk-amd64
            java -version
      - checkout
      - restore_cache:
          key: maven-dependencies-{{ checksum "pom.xml" }}
      - run: ./integration_test_suite/pull-smoke-test-docker-images.sh
      - run: ./mvnw clean install
      - run: ./mvnw javadoc:jar
      - save_cache:
          paths:
            - ~/.m2
          key: maven-dependencies-{{ checksum "pom.xml" }}
orbs:
  prometheus: prometheus/prometheus@0.16.0
