name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'corretto'
          cache: maven
      - name: Build
        run: |
          ./run-quick-test.sh
          ./mvnw --batch-mode javadoc:jar
