name: Deploy Documentation

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    if: github.repository == 'prometheus/jmx_exporter'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v6
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: npm
          cache-dependency-path: website/package-lock.json
      - name: Build documentation
        run: ./scripts/build-documentation.sh
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./website/build

  deploy:
    if: github.repository == 'prometheus/jmx_exporter'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
