on:
  release:
    types: [released]
name: Build, test and publish
jobs:
  buildDockerImage:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Login to Artifactory
      uses: docker/login-action@v1 
      with:
        registry: artifactory.internal.sysdig.com
        username: david.lorite@sysdig.com
        password: ${{ secrets.ARTI_TOKEN }}
    - name: Release if tagged
      if: "!startswith(github.ref, 'refs/tags/v')"
      run: exit 78
    - name: Build image
      run: |
        docker build --label version=${{ github.event.release.tag_name }} -f ./build/Dockerfile -t artifactory.internal.sysdig.com/jmx-exporter:latest .
        docker build --label version=${{ github.event.release.tag_name }} -f ./build/Dockerfile.jre11 -t temp-jmx-exporter:${{ github.event.release.tag_name }}-ubi .
    - name: Publish docker image
      run: |
        docker tag artifactory.internal.sysdig.com/jmx-exporter:latest artifactory.internal.sysdig.com/jmx-exporter:${{ github.event.release.tag_name }}
        docker push artifactory.internal.sysdig.com/jmx-exporter:${{ github.event.release.tag_name }}
        docker push artifactory.internal.sysdig.com/jmx-exporter:${{ github.event.release.tag_name }}-ubi
        docker push artifactory.internal.sysdig.com/jmx-exporter:latest