name: Scheduled Build (every hour)
on:
  schedule:
    - cron: "0 * * * *"
jobs:
  build:
    if: github.repository == 'prometheus/jmx_exporter'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven
      - name: Build
          ./integration_test_suite/pull-smoke-test-docker-images.sh
          ./mvnw --batch-mode clean install
          ./mvnw --batch-mode javadoc:jar